vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        officier:
            uri_prefix: /images/officier
            upload_destination: '%kernel.project_dir%/public/images/officier'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
